"""Language code/name tables for RealtimeSTT (faster-whisper, ~99 languages)
and Local NLLB (FLORES-200, ~200 languages).

Neither faster-whisper nor the transformers NLLB tokenizer ship a
human-readable display name alongside their language codes, so this module
hand-maintains one. The code sets themselves are validated (see
test/scratch checks during development) against the installed packages'
own `faster_whisper.tokenizer._LANGUAGE_CODES` and
`transformers.models.nllb.tokenization_nllb.FAIRSEQ_LANGUAGE_CODES` so the
codes here are guaranteed real, not guessed.

WHISPER_LANGUAGES: whisper/RealtimeSTT code -> (display name, FLORES-200
code or None if NLLB has no equivalent language).
NLLB_ONLY_LANGUAGES: FLORES-200 code -> display name, for the languages
NLLB supports that RealtimeSTT/Whisper does not.
"""

WHISPER_LANGUAGES = {
    "af": ("Afrikaans", "afr_Latn"),
    "am": ("Amharic", "amh_Ethi"),
    "ar": ("Arabic", "arb_Arab"),
    "as": ("Assamese", "asm_Beng"),
    "az": ("Azerbaijani", "azj_Latn"),
    "ba": ("Bashkir", "bak_Cyrl"),
    "be": ("Belarusian", "bel_Cyrl"),
    "bg": ("Bulgarian", "bul_Cyrl"),
    "bn": ("Bengali", "ben_Beng"),
    "bo": ("Tibetan", "bod_Tibt"),
    "br": ("Breton", None),
    "bs": ("Bosnian", "bos_Latn"),
    "ca": ("Catalan", "cat_Latn"),
    "cs": ("Czech", "ces_Latn"),
    "cy": ("Welsh", "cym_Latn"),
    "da": ("Danish", "dan_Latn"),
    "de": ("German", "deu_Latn"),
    "el": ("Greek", "ell_Grek"),
    "en": ("English", "eng_Latn"),
    "es": ("Spanish", "spa_Latn"),
    "et": ("Estonian", "est_Latn"),
    "eu": ("Basque", "eus_Latn"),
    "fa": ("Persian", "pes_Arab"),
    "fi": ("Finnish", "fin_Latn"),
    "fo": ("Faroese", "fao_Latn"),
    "fr": ("French", "fra_Latn"),
    "gl": ("Galician", "glg_Latn"),
    "gu": ("Gujarati", "guj_Gujr"),
    "ha": ("Hausa", "hau_Latn"),
    "haw": ("Hawaiian", None),
    "he": ("Hebrew", "heb_Hebr"),
    "hi": ("Hindi", "hin_Deva"),
    "hr": ("Croatian", "hrv_Latn"),
    "ht": ("Haitian Creole", "hat_Latn"),
    "hu": ("Hungarian", "hun_Latn"),
    "hy": ("Armenian", "hye_Armn"),
    "id": ("Indonesian", "ind_Latn"),
    "is": ("Icelandic", "isl_Latn"),
    "it": ("Italian", "ita_Latn"),
    "ja": ("Japanese", "jpn_Jpan"),
    "jw": ("Javanese", "jav_Latn"),
    "ka": ("Georgian", "kat_Geor"),
    "kk": ("Kazakh", "kaz_Cyrl"),
    "km": ("Khmer", "khm_Khmr"),
    "kn": ("Kannada", "kan_Knda"),
    "ko": ("Korean", "kor_Hang"),
    "la": ("Latin", None),
    "lb": ("Luxembourgish", "ltz_Latn"),
    "ln": ("Lingala", "lin_Latn"),
    "lo": ("Lao", "lao_Laoo"),
    "lt": ("Lithuanian", "lit_Latn"),
    "lv": ("Latvian", "lvs_Latn"),
    "mg": ("Malagasy", "plt_Latn"),
    "mi": ("Maori", "mri_Latn"),
    "mk": ("Macedonian", "mkd_Cyrl"),
    "ml": ("Malayalam", "mal_Mlym"),
    "mn": ("Mongolian", "khk_Cyrl"),
    "mr": ("Marathi", "mar_Deva"),
    "ms": ("Malay", "zsm_Latn"),
    "mt": ("Maltese", "mlt_Latn"),
    "my": ("Burmese", "mya_Mymr"),
    "ne": ("Nepali", "npi_Deva"),
    "nl": ("Dutch", "nld_Latn"),
    "nn": ("Norwegian Nynorsk", "nno_Latn"),
    "no": ("Norwegian", "nob_Latn"),
    "oc": ("Occitan", "oci_Latn"),
    "pa": ("Punjabi", "pan_Guru"),
    "pl": ("Polish", "pol_Latn"),
    "ps": ("Pashto", "pbt_Arab"),
    "pt": ("Portuguese", "por_Latn"),
    "ro": ("Romanian", "ron_Latn"),
    "ru": ("Russian", "rus_Cyrl"),
    "sa": ("Sanskrit", "san_Deva"),
    "sd": ("Sindhi", "snd_Arab"),
    "si": ("Sinhala", "sin_Sinh"),
    "sk": ("Slovak", "slk_Latn"),
    "sl": ("Slovenian", "slv_Latn"),
    "sn": ("Shona", "sna_Latn"),
    "so": ("Somali", "som_Latn"),
    "sq": ("Albanian", "als_Latn"),
    "sr": ("Serbian", "srp_Cyrl"),
    "su": ("Sundanese", "sun_Latn"),
    "sv": ("Swedish", "swe_Latn"),
    "sw": ("Swahili", "swh_Latn"),
    "ta": ("Tamil", "tam_Taml"),
    "te": ("Telugu", "tel_Telu"),
    "tg": ("Tajik", "tgk_Cyrl"),
    "th": ("Thai", "tha_Thai"),
    "tk": ("Turkmen", "tuk_Latn"),
    "tl": ("Tagalog", "tgl_Latn"),
    "tr": ("Turkish", "tur_Latn"),
    "tt": ("Tatar", "tat_Cyrl"),
    "uk": ("Ukrainian", "ukr_Cyrl"),
    "ur": ("Urdu", "urd_Arab"),
    "uz": ("Uzbek", "uzn_Latn"),
    "vi": ("Vietnamese", "vie_Latn"),
    "yi": ("Yiddish", "ydd_Hebr"),
    "yo": ("Yoruba", "yor_Latn"),
    "yue": ("Cantonese", "yue_Hant"),
    "zh": ("Chinese", "zho_Hans"),
}

NLLB_ONLY_LANGUAGES = {
    "ace_Arab": "Acehnese (Arabic script)",
    "ace_Latn": "Acehnese",
    "acm_Arab": "Mesopotamian Arabic",
    "acq_Arab": "Ta'izzi-Adeni Arabic",
    "aeb_Arab": "Tunisian Arabic",
    "ajp_Arab": "South Levantine Arabic",
    "aka_Latn": "Akan",
    "apc_Arab": "North Levantine Arabic",
    "ars_Arab": "Najdi Arabic",
    "ary_Arab": "Moroccan Arabic",
    "arz_Arab": "Egyptian Arabic",
    "ast_Latn": "Asturian",
    "awa_Deva": "Awadhi",
    "ayr_Latn": "Central Aymara",
    "azb_Arab": "South Azerbaijani",
    "bam_Latn": "Bambara",
    "ban_Latn": "Balinese",
    "bem_Latn": "Bemba",
    "bho_Deva": "Bhojpuri",
    "bjn_Arab": "Banjar (Arabic script)",
    "bjn_Latn": "Banjar",
    "bug_Latn": "Buginese",
    "ceb_Latn": "Cebuano",
    "cjk_Latn": "Chokwe",
    "ckb_Arab": "Central Kurdish",
    "crh_Latn": "Crimean Tatar",
    "dik_Latn": "Southwestern Dinka",
    "dyu_Latn": "Dyula",
    "dzo_Tibt": "Dzongkha",
    "epo_Latn": "Esperanto",
    "ewe_Latn": "Ewe",
    "fij_Latn": "Fijian",
    "fon_Latn": "Fon",
    "fur_Latn": "Friulian",
    "fuv_Latn": "Nigerian Fulfulde",
    "gaz_Latn": "West Central Oromo",
    "gla_Latn": "Scottish Gaelic",
    "gle_Latn": "Irish",
    "grn_Latn": "Guarani",
    "hne_Deva": "Chhattisgarhi",
    "ibo_Latn": "Igbo",
    "ilo_Latn": "Ilocano",
    "kab_Latn": "Kabyle",
    "kac_Latn": "Jingpho",
    "kam_Latn": "Kamba",
    "kas_Arab": "Kashmiri (Arabic script)",
    "kas_Deva": "Kashmiri (Devanagari script)",
    "kbp_Latn": "Kabiye",
    "kea_Latn": "Kabuverdianu",
    "kik_Latn": "Kikuyu",
    "kin_Latn": "Kinyarwanda",
    "kir_Cyrl": "Kyrgyz",
    "kmb_Latn": "Kimbundu",
    "kmr_Latn": "Northern Kurdish",
    "knc_Arab": "Central Kanuri (Arabic script)",
    "knc_Latn": "Central Kanuri",
    "kon_Latn": "Kikongo",
    "lij_Latn": "Ligurian",
    "lim_Latn": "Limburgish",
    "lmo_Latn": "Lombard",
    "ltg_Latn": "Latgalian",
    "lua_Latn": "Luba-Kasai",
    "lug_Latn": "Ganda",
    "luo_Latn": "Luo",
    "lus_Latn": "Mizo",
    "mag_Deva": "Magahi",
    "mai_Deva": "Maithili",
    "min_Latn": "Minangkabau",
    "mni_Beng": "Manipuri",
    "mos_Latn": "Mossi",
    "nso_Latn": "Northern Sotho",
    "nus_Latn": "Nuer",
    "nya_Latn": "Nyanja",
    "ory_Orya": "Odia",
    "pag_Latn": "Pangasinan",
    "pap_Latn": "Papiamento",
    "prs_Arab": "Dari",
    "quy_Latn": "Ayacucho Quechua",
    "run_Latn": "Rundi",
    "sag_Latn": "Sango",
    "sat_Beng": "Santali",
    "scn_Latn": "Sicilian",
    "shn_Mymr": "Shan",
    "smo_Latn": "Samoan",
    "sot_Latn": "Southern Sotho",
    "srd_Latn": "Sardinian",
    "ssw_Latn": "Swati",
    "szl_Latn": "Silesian",
    "taq_Latn": "Tamasheq",
    "taq_Tfng": "Tamasheq (Tifinagh script)",
    "tir_Ethi": "Tigrinya",
    "tpi_Latn": "Tok Pisin",
    "tsn_Latn": "Tswana",
    "tso_Latn": "Tsonga",
    "tum_Latn": "Tumbuka",
    "twi_Latn": "Twi",
    "tzm_Tfng": "Central Atlas Tamazight",
    "uig_Arab": "Uyghur",
    "umb_Latn": "Umbundu",
    "vec_Latn": "Venetian",
    "war_Latn": "Waray",
    "wol_Latn": "Wolof",
    "xho_Latn": "Xhosa",
    "zho_Hant": "Chinese (Traditional)",
    "zul_Latn": "Zulu",
}

WHISPER_LANGUAGE_NAMES = {code: name for code, (name, _flores) in WHISPER_LANGUAGES.items()}

NLLB_LANGUAGE_NAMES = {
    flores: name for _code, (name, flores) in WHISPER_LANGUAGES.items() if flores
}
NLLB_LANGUAGE_NAMES.update(NLLB_ONLY_LANGUAGES)


def whisper_language_options():
    """(display name, code) pairs for all RealtimeSTT/Whisper languages,
    sorted by name."""
    return sorted(
        ((name, code) for code, name in WHISPER_LANGUAGE_NAMES.items()),
        key=lambda item: item[0].lower(),
    )


def nllb_language_options():
    """(display name, FLORES-200 code) pairs for all Local NLLB languages,
    sorted by name."""
    return sorted(
        ((name, flores) for flores, name in NLLB_LANGUAGE_NAMES.items()),
        key=lambda item: item[0].lower(),
    )
